Pusher.app_id = ENV["pusher_app_id"]
Pusher.key    = ENV["pusher_key"]
Pusher.secret = ENV["pusher_secret"]

SENDGRID_USERNAME = ENV["SENDGRID_USERNAME"]
SENDGRID_PASSWORD = ENV["SENDGRID_PASSWORD"]
DOMAIN_NAME = ENV["DOMAIN_NAME"]  

GMAIL_USERNAME = ENV["GMAIL_USERNAME"]
GMAIL_PASSWORD = ENV["GMAIL_PASSWORD"]

FACEBOOK_KEY = ENV["FACEBOOK_KEY"]
FACEBOOK_SECRET = ENV["FACEBOOK_SECRET"]